title:            misunderheard
description:      Varied ramblings on science, code and economics.
disqus_shortname: misunderheard
reading_time:     true
words_per_minute: 200
logo:             
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
# url: http://aronbordin.com/neo-hpstr-jekyll-theme

menu:
  - title: 'home'
    url: '/'
  - title: 'tags'
    url: '/tags'
  - title: 'projects'
    url: '#'
    submenu:
      - title: 'Foraminiferal assemblage modelling in Python'
        url: '/foram_python/'
      - title: 'Monetary economics in Python'
        url: '/monetary_economics/'
  - title: 'about'
    url: '/about'

# Owner/author information
owner:
  name:           Andrew Berkeley
  site:           http://spatchcock.github.io
  avatar:         images/avatar.jpg
  bio:            "Your bio goes here."
  email:          andrew.berkeley.is@googlemail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: spatchcockable
  facebook:
  github: spatchcock
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +AronBordin
  google_plus:

social:
  - title: "github"
    url: "https://github.com/spatchcock"
  - title: "twitter"
    url: "https://twitter.com/spatchcockable"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
excerpt_separator: "<!--break-->"